---
title: Matthew Clance
---

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FEVK27LWND"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FEVK27LWND');
</script>

# About me

Matthew Clance is an Associate Professor at the University of Pretoria and a Fellow at Pan-African Scientific Council. His background includes applied econometrics and geospatial analysis of micro Big Data and he has worked on various projects related to the Lancet Commission and African Climate Policy Center projects. Related areas include climate change and geographic features on health outcomes, structural transformation, and conflict and development. He has supervised PhD and Postdoc studies on international trade, structural transformation, and gender inequality in Sub-Saharan Africa.

Matthew’s research interests include the connection between international trade and development and geospatial econometric analysis of inequality and conflict determinants. He has experience working with the Federal Reserve bank of Atlanta as a Research Associate and worked on various Lancet Commission and African Climate Policy Center projects. His research has appeared in Journal of Development Economics, The Journal of Development Studies, Applied Economics, Food Policy, Tourism Economics, among others.