---
title: Matthew Clance
---

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FEVK27LWND"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FEVK27LWND');
</script>

# About me

Matthew Clance is an Associate Professor at the University of Pretoria and a Fellow at Pan-African Scientific Council. His background includes applied econometrics and geospatial analysis of micro Big Data and he has worked on various projects related to the Lancet Commission and African Climate Policy Center projects. Related areas include climate change and geographic features on health outcomes, impacts of restrictions on Covid-19 death rates, and conflict and development. He has supervised PhD and Postdoc studies on gender inequality in Sub-Saharan Africa.

Matthew’s research interests include the connection between international trade and development and geospatial econometric analysis of inequality and conflict determinants. He has experience working with the Federal Reserve bank of Atlanta as a Research Associate and worked on various Lancet Commission and African Climate Policy Center projects. His research has appeared in Journal of Development Economics, Food Policy, Applied Economic Letters, Tourism Economics, and Sustainability, among others.

# Research Visibility

- [Curriculum Vitae](Clance.CV.pdf)
- [Google Scholar](https://bit.ly/3hm23Oq)
- [RePEc](https://ideas.repec.org/e/pcl147.html)
- [ORCID](https://orcid.org/0000-0002-9280-7324)
- [WOS](https://www.webofscience.com/wos/author/record/1802162)

# Selected Publications

van der Merwe, E., Clance, M., and Yitbarek, E. (2022). Climate change and child malnutrition: A nigerian perspective. Food Policy, page 102281 https://doi.org/10.1016/j.foodpol.2022.102281

Bosch, A., Clance, M., and Koch, S. F. (2022). Household debt and consumption dynamics a non-developed world view following the financial crisis. Applied Economics, 54(8):897–917 https://doi.org/10.1080/00036846.2021.1969004

Chisadza, C., Clance, M., and Gupta, R. (2021a). Government effectiveness and the covid-19 pandemic. Sustainability, 13(6) https://doi.org/10.3390/su13063042

Chisadza, C., Clance, M., Gupta, R., and Wanke, P. (2020). Uncertainty and tourism in africa. Tourism Economics, https://doi.org/10.1177/1354816620969998

Baier, Scott, Jeffrey Bergstrand, Matthew Clance, (2018) “Heterogeneous Effects of Economic Integration Agreements.” Journal of Development Economics, Elsevier, vol. 135(C), pages 587-608 https://doi.org/10.1016/j.jdeveco.2018.08.014