---
title: "Teaching"
output: html_document
---

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FEVK27LWND"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-FEVK27LWND');
</script>


- **Honours Level:**
  - Econometrics
    - [Introduction to R: EKT 795 (Created by Eduard van der Merwe)](https://drive.google.com/drive/folders/1eiTd0ZcpTPae0Z89AFLKPtMIhTnciUM3?usp=drive_link)
    - [Introduction to Stata: EKT 795](https://drive.google.com/drive/folders/1FPnumlSxkKO3raxLevHkms6WJb3IIcpt?usp=sharing)
  - Microeconomics
  - International Trade
- **Graduate Level:**
  - Econometrics (Cross Section and Panel)
  - Development Economics
  - International Trade
- **Short Courses:**
  - ERSA Workshop (2015-2026)
    - Cross Sectional Econometrics 
      - [Class Folder 2025](https://drive.google.com/drive/folders/1T8FaJMw3BugT5wnfRvcT4UWuw1UxEyDG?usp=sharing)
    - Panel Econometrics
      - [Class Folder 2026](https://drive.google.com/drive/folders/1qFdLLUn2pSPZF8p9qRDebkGrYAPm4Gnc?usp=sharing)
  - R Introduction (University of Notre Dame - 2022)
    - Additional material for setup (including RMarkdown) available [here](setup-guide.html)
  - Introduction to Quantile Gravity (USITC - 2025)
  - Mathematics for Economists (SARB - 2025)

## Postgraduate Supervision

Matthew has supervised or co-supervised 5 completed PhDs and 22 completed master's degrees, and currently supervises 8 PhD and 3 master's students.

**Completed PhDs:**

- Sibonelo P.N. Mbambo (2024), "Essays on spatial effects of public school infrastructure on growth and inequality" (co-supervisor)
- Blessing Chipanda (2022), "Essays on technological trade composition and capital goods imports"
- Leoné Walters (2022), "Essays on socio-political factors and economic development" (co-supervisor)
- Tendai Zawaira (2021), "Essays on gender, growth and development in Africa"
- Adél Bosch (2020), "Quantifying household deleveraging following the 2007 South African financial cycle peak" (co-supervisor)